# Generated by Django 4.1 on 2022-09-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=30)),
                ('categoria', models.CharField(choices=[('T', 'Terror'), ('C', 'Comedia'), ('F', 'Fantasia')], default='T', max_length=1)),
            ],
        ),
    ]
