# Generated by Django 4.1 on 2022-09-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appuno', '0002_alter_libros_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='edad',
            field=models.DateTimeField(blank=True, default='11/09/2022'),
        ),
    ]
