# Generated by Django 4.1 on 2022-09-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appuno', '0003_libros_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='edad',
            field=models.DateTimeField(blank=True, default='2022-09-11'),
        ),
    ]
