# Generated by Django 4.1 on 2022-09-12 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appuno', '0004_alter_libros_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='edad',
            field=models.DateTimeField(blank=True, default=datetime.date(2022, 9, 11)),
        ),
    ]
