# Generated by Django 4.1 on 2022-09-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appuno', '0006_alter_libros_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='edad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
